-- ============================================================
-- AWADI Database Schema for Supabase (PostgreSQL)
-- Created: 2026-02-24
--
-- Source tables:
--   tbldef_anl_typen  → anl_typen
--   tblkunden
--   tblanl_eigentuemer  → kunden   (merged; EigentuemerNr = KundenNr)
--   tblanl              → anlagen
--   tblanl_bio          → anl_biologien
--   (derived)           → kontakte, wartungsvertraege
-- ============================================================


-- ============================================================
-- 1. ANL_TYPEN  —  Plant / Treatment Type Master Data
--
--    Source: tbldef_anl_typen
--    Defines maintenance intervals and on-site duration per type.
--    The BioFelder column holds a pipe-delimited list of
--    inspection-form field identifiers used by the maintenance app.
-- ============================================================
create table public.anl_typen (
  id                        integer primary key,        -- DefAnlTypenID (legacy)
  sortiernr                 integer,
  bezeichnung               text not null,

  -- Pipe-delimited list of biology/inspection field IDs for this type
  -- e.g. "|BtrStdZaehler|Lueftung|SchachtAbd|..."
  bio_felder                text,

  -- Pricing master data (can be overridden per Wartungsvertrag)
  preis_je_wartung          numeric(10,2) not null default 0,
  preis_je_kontrolle        numeric(10,2) not null default 0,

  -- Maintenance scheduling master data (override possible per contract)
  wartungsintervall_monate  integer not null default 12,
  dauer_wartung_minuten     integer not null default 60,
  dauer_kontrolle_minuten   integer,

  comment                   text,
  last_update               timestamptz,
  created_at                timestamptz not null default now()
);


-- ============================================================
-- 2. KUNDEN  —  Customers / Owners
--
--    Merged from tblkunden + tblanl_eigentuemer.
--    Business key: kundennr (= KundenNr = EigentuemerNr, e.g. "AS-201").
--    A customer who has ≥ 1 facility assigned is implicitly an owner
--    (no separate owner table needed — see view "eigentuemer" below).
-- ============================================================
create table public.kunden (
  id                    integer generated by default as identity primary key,

  -- Business key preserved from legacy (KundenNr / EigentuemerNr)
  kundennr              text unique,

  -- IstKunde=false means the record exists only as an owner/contact,
  -- not as an active paying customer.
  ist_kunde             boolean not null default true,

  -- Person / organisation
  firma                 text,
  nachname              text,
  vorname               text,
  titel                 text,
  anrede                text,

  -- Address
  strasse               text,
  hausnr                text,
  laenderkennung        varchar(5),
  plz                   varchar(10),
  ort                   text,
  ortsteil              text,

  -- Contact channels
  telefonnr             text,
  telefonnr_geschaeft   text,
  mobilnr               text,
  mobilnr2              text,
  faxnr                 text,
  email                 text,
  homepage              text,

  -- Notes
  comment               text,
  -- Maps to both InterneAnmerkungen (tblkunden) and Anmerkungen (tblanl_eigentuemer)
  interne_anmerkungen   text,
  bezeichnung           text,

  -- Legacy tracking fields
  trace_mark            integer,
  last_update           timestamptz,
  created_at            timestamptz not null default now()
);


-- ============================================================
-- 3. KONTAKTE  —  Standalone Maintenance Contacts
--
--    Used when the contact person for a facility is not
--    a registered customer (e.g. a tenant, caretaker, etc.).
--    In the UI: user can either pick a Kunde or fill in these
--    fields directly → stored here.
-- ============================================================
create table public.kontakte (
  id                    integer generated by default as identity primary key,

  firma                 text,
  nachname              text,
  vorname               text,
  titel                 text,
  anrede                text,

  strasse               text,
  hausnr                text,
  laenderkennung        varchar(5),
  plz                   varchar(10),
  ort                   text,
  ortsteil              text,

  telefonnr             text,
  mobilnr               text,
  email                 text,
  anmerkungen           text,

  last_update           timestamptz,
  created_at            timestamptz not null default now()
);


-- ============================================================
-- 4. ANLAGEN  —  Facilities / Wastewater Treatment Plants
--
--    Source: tblanl
--    Each facility belongs to exactly one Kunde (= the owner).
--    The maintenance contact is modelled as an XOR:
--      • kontakt_kunde_id  → an existing Kunde is the contact
--      • kontakt_id        → a standalone Kontakt is the contact
--      • both null         → no specific contact (use owner data)
-- ============================================================
create table public.anlagen (
  id                          integer primary key,        -- AnlID (preserved from legacy)

  -- Owner: always a registered customer
  kunden_id                   integer not null
                                 references public.kunden(id)
                                 on update cascade on delete restrict,

  ist_aktiv                   boolean not null default true,  -- IstAktiv

  -- Unique plant identifier (e.g. "AS-290", "PS-Dax", "FB-21145")
  anlagen_nr                  text unique,

  -- Treatment process: number of pre-treatment containers
  verfahren_br_anz_behaelter  integer,

  -- Facility address (may differ from owner address)
  strasse                     text,
  hausnr                      text,
  laenderkennung              varchar(5),
  plz                         varchar(10),
  ort                         text,
  ortsteil                    text,

  -- Cadastral data
  gemarkung                   text,
  flur                        text,
  flurstueck                  text,

  -- Coordinates (stored as original strings; "0000000" = not set)
  rechtswert                  text,
  hochwert                    text,
  breitengrad                 text,     -- e.g. "00°  00´  00,0´´"
  laengengrad                 text,

  -- Sizing
  anlage_ausgelegt_ew         integer,  -- design capacity in population equivalents
  tatsaechliche_ew            integer,  -- actual population equivalents
  gesamtgroesse_vk            numeric(12,2),

  -- Tour / route planning (stored as text; can be "50", "125", etc.)
  touren_nr                   text,
  touren_nr2                  text,
  touren_nr3                  text,

  -- Scheduling
  datum_naechste_wartung      date,
  datum_abgabefrei_seit       date,     -- date facility became exempt from reporting

  -- Legacy contract fields from tblanl
  -- (Wartungsvertrag: 1 = active contract, 2 = passive/special)
  wartungsvertrag_flag        smallint
                                 constraint anlagen_wv_flag_check
                                 check (wartungsvertrag_flag in (1, 2)),
  datum_wartungsvertrag       text,     -- stored as "DD.MM.YYYY" in source

  -- Export flag for maintenance scheduling export
  export_erlaubt_wartung      boolean not null default true,

  -- ── Maintenance contact (XOR: at most one may be set) ──────────────
  -- Option A: contact is a registered customer
  kontakt_kunde_id            integer
                                 references public.kunden(id)
                                 on update cascade on delete set null,
  -- Option B: contact is a standalone (non-customer) contact
  kontakt_id                  integer
                                 references public.kontakte(id)
                                 on update cascade on delete set null,

  -- Legacy import: raw Ansprechpartner text from tblanl
  -- (free-text, often "Name" or "Name, Phone"; preserved for reference)
  ansprechpartner_legacy      text,
  telefonnr_legacy            text,     -- TelefonNr field from tblanl (facility-side phone)
  -- ───────────────────────────────────────────────────────────────────

  comment                     text,
  anmerkungen_gesamt          text,
  bezeichnung                 text,

  -- Legacy tracking fields
  trace_mark                  integer,
  last_update                 timestamptz,
  last_export                 timestamptz,
  last_import                 timestamptz,
  created_at                  timestamptz not null default now(),

  -- At most one contact reference may be set at a time
  constraint anlagen_kontakt_xor check (
    num_nonnulls(kontakt_kunde_id, kontakt_id) <= 1
  )
);


-- ============================================================
-- 5. ANL_BIOLOGIEN  —  Biological / Treatment Process Data
--
--    Source: tblanl_bio
--    Each facility has exactly 4 records (BioNummer 1..4) in the
--    legacy data, but only records with vorhanden=true are active.
--    In practice: 1 vorhanden biology per facility (3 have 2).
--    The model allows any number > 0, enforced by the unique
--    constraint on (anlage_id, bio_nummer).
--
--    The K2..K17 columns represent technology-specific parameters.
--    Only the columns relevant to the chosen anl_typ_id will
--    contain data; all others are null.
-- ============================================================
create table public.anl_biologien (
  id                        integer primary key,        -- AnlBioID (preserved from legacy)

  anlage_id                 integer not null
                               references public.anlagen(id)
                               on update cascade on delete cascade,

  -- Sequence number within the facility (1..4 in legacy, open-ended here)
  bio_nummer                smallint not null
                               constraint anl_biologien_bio_nummer_check
                               check (bio_nummer >= 1),

  -- false = slot exists in legacy but has no real data
  vorhanden                 boolean not null default false,

  -- Device / system identification
  hersteller                text,
  typ                       text,

  -- Treatment type reference → determines which K-columns are relevant
  anl_typ_id                integer
                               references public.anl_typen(id)
                               on update cascade on delete set null,

  -- ── K2: Untergrundverrieselung / Rieselrohranlage ──────────────────
  k2_anzahl_straenge        numeric(10,2),
  k2_gesamtlaenge           numeric(10,2),
  k2_stossbeschickung       smallint,       -- 0/1 boolean flag

  -- ── K3: Filtergraben ───────────────────────────────────────────────
  k3_anzahl_straenge        numeric(10,2),
  k3_gesamtlaenge           numeric(10,2),
  k3_stossbeschickung       smallint,

  -- ── K5: Pflanzenklaeranlage horizontal ─────────────────────────────
  k5_oberflaeche            numeric(10,2),
  k5_beettiefe              numeric(10,2),
  k5_stossbeschickung       smallint,

  -- ── K6: Membrananlage ──────────────────────────────────────────────
  k6_reaktorvolumen         numeric(10,2),
  k6_membranflaeche         numeric(10,2),

  -- ── K7: Teichanlage (belüftet / unbelüftet) ────────────────────────
  k7_belueftet              smallint,       -- 0/1
  k7_gesamtvolumen          numeric(10,2),
  k7_oberflaeche            numeric(10,2),
  k7_tiefe                  numeric(10,2),

  -- ── K8: Pflanzenklaeranlage vertikal ───────────────────────────────
  k8_oberflaeche            numeric(10,2),
  k8_beettiefe              numeric(10,2),
  k8_stossbeschickung       smallint,

  -- ── K9: (application-specific) ─────────────────────────────────────
  k9_oberflaeche            numeric(10,2),
  k9_beettiefe              numeric(10,2),

  -- ── K10: Tropfkoerperanlage ─────────────────────────────────────────
  k10_beschickung           smallint,
  k10_volumen               numeric(10,2),
  k10_ruecklaufverhaeltnis  numeric(10,2),

  -- ── K12: Festbettanlage ─────────────────────────────────────────────
  k12_reaktorvolumen        numeric(10,2),
  k12_spez_oberflaeche      numeric(10,2),
  k12_oberflaeche           numeric(10,2),

  -- ── K13: Rotations-Tauchkoerperanlage ───────────────────────────────
  k13_reaktorvolumen        numeric(10,2),
  k13_spez_oberflaeche      numeric(10,2),
  k13_oberflaeche           numeric(10,2),

  -- ── K14: Sonstiges (generic, named parameters) ──────────────────────
  k14_verfahren             text,
  k14_kenngroesse1_art      text,
  k14_kenngroesse1_wert     numeric(10,2),
  k14_kenngroesse2_art      text,
  k14_kenngroesse2_wert     numeric(10,2),

  -- ── K15: Belebungsanlage ─────────────────────────────────────────────
  k15_reaktorvolumen        numeric(10,2),
  k15_ts_gehalt             numeric(10,2),

  -- ── K16: SBR-Anlage ─────────────────────────────────────────────────
  k16_reaktorvolumen        numeric(10,2),
  k16_ts_gehalt             numeric(10,2),
  k16_austauschvolumen      numeric(10,2),

  -- ── K17: Wirbelbettanlage ────────────────────────────────────────────
  k17_reaktorvolumen        numeric(10,2),
  k17_spez_oberflaeche      numeric(10,2),
  k17_oberflaeche           numeric(10,2),

  -- ── Compliance & certification ────────────────────────────────────────
  netzunabh_alarm           smallint,       -- 0/1: independent network alarm present
  schlamm_kompost           smallint,       -- 0/1: sludge composting
  bauaufs_zul               text,           -- building authority approval reference
  bauaufs_zul_link_datei    text,           -- link to approval document file
  bauaufs_zul_link_bez      text,           -- link label (BauaufszulLinktBezeichnung)

  bio_gueltig_bis           date,
  bio_reinigungsklassen     smallint,       -- treatment class (0/1/2)
  bio_zus_reinigungsklasse  smallint,       -- additional treatment class

  comment                   text,
  anmerkungen_biologie      text,
  last_update               timestamptz,
  created_at                timestamptz not null default now(),

  unique (anlage_id, bio_nummer)
);


-- ============================================================
-- 6. WARTUNGSVERTRAEGE  —  Maintenance Contracts
--
--    Derived from tblanl (DatumWartungsvertrag, Wartungsvertrag flag).
--    One facility can have multiple contracts over time.
--    Pricing and interval overrides take precedence over anl_typen defaults.
-- ============================================================
create table public.wartungsvertraege (
  id                      integer generated by default as identity primary key,

  anlage_id               integer not null
                             references public.anlagen(id)
                             on update cascade on delete cascade,

  -- Contracting party (normally the facility owner)
  kunden_id               integer
                             references public.kunden(id)
                             on update cascade on delete set null,

  vertragsnummer          text,
  vertragsdatum           date,           -- DatumWartungsvertrag (parsed from tblanl)
  gueltig_ab              date,
  gueltig_bis             date,

  -- Plant type that applies to this contract
  anl_typ_id              integer
                             references public.anl_typen(id)
                             on update cascade on delete set null,

  -- Contract-level overrides (null = inherit from anl_typen)
  intervall_monate        integer,
  dauer_wartung_minuten   integer,
  preis_je_wartung        numeric(10,2),

  aktiv                   boolean not null default true,

  comment                 text,
  last_update             timestamptz,
  created_at              timestamptz not null default now()
);


-- ============================================================
-- INDEXES
-- ============================================================

-- kunden
create index on public.kunden (kundennr);
create index on public.kunden (nachname, vorname);
create index on public.kunden (ist_kunde);

-- anlagen
create index on public.anlagen (kunden_id);
create index on public.anlagen (ist_aktiv);
create index on public.anlagen (touren_nr);
create index on public.anlagen (kontakt_kunde_id);
create index on public.anlagen (kontakt_id);
create index on public.anlagen (anlagen_nr);

-- anl_biologien
create index on public.anl_biologien (anlage_id);
create index on public.anl_biologien (anlage_id, vorhanden);
create index on public.anl_biologien (anl_typ_id);

-- wartungsvertraege
create index on public.wartungsvertraege (anlage_id);
create index on public.wartungsvertraege (kunden_id);
create index on public.wartungsvertraege (aktiv);


-- ============================================================
-- VIEWS
-- ============================================================

-- eigentuemer: customers who own at least one facility
create or replace view public.eigentuemer as
select distinct k.*
from public.kunden k
join public.anlagen a on a.kunden_id = k.id;

-- anlagen_details: flat view combining facility with owner and contact info
create or replace view public.anlagen_details as
select
  a.*,

  -- Owner data
  k.kundennr                        as owner_kundennr,
  coalesce(k.firma,
    concat_ws(' ', k.vorname, k.nachname))
                                    as owner_name,
  k.telefonnr                       as owner_telefonnr,
  k.email                           as owner_email,

  -- Resolved contact: either a Kunde or a standalone Kontakt
  case
    when a.kontakt_kunde_id is not null then 'kunde'
    when a.kontakt_id        is not null then 'kontakt'
    else null
  end                               as kontakt_typ,

  coalesce(
    concat_ws(' ', kk.vorname, kk.nachname),
    concat_ws(' ', kont.vorname, kont.nachname)
  )                                 as kontakt_name,

  coalesce(kk.telefonnr, kont.telefonnr)  as kontakt_telefonnr,
  coalesce(kk.email,     kont.email)      as kontakt_email

from public.anlagen a
join public.kunden k
  on k.id = a.kunden_id
left join public.kunden kk
  on kk.id = a.kontakt_kunde_id
left join public.kontakte kont
  on kont.id = a.kontakt_id;
